name: Build-Angle

on: push

jobs:
  build-angle:
    name: Build ANGLE
    runs-on: macos-latest
      
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Add Depot Tools to PATH
        run: |
          echo "$env:GITHUB_WORKSPACE/depot_tools" >> $env:GITHUB_PATH
          echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" >> $env:GITHUB_ENV
        
      - name: Sync
        run: |
            python scripts/bootstrap.py
            gclient sync
            git checkout master
        working-directory: angle
      
      - name: Build
        run: |
          gn gen out/Release --args="is_debug = false"
          autoninja -C out/Release
        working-directory: angle

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out-Release-macos
          path: angle/out/Release